//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevicePartition) DeepCopyInto(out *BlockDevicePartition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevicePartition.
func (in *BlockDevicePartition) DeepCopy() *BlockDevicePartition {
	if in == nil {
		return nil
	}
	out := new(BlockDevicePartition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockStorageMapping) DeepCopyInto(out *BlockStorageMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockStorageMapping.
func (in *BlockStorageMapping) DeepCopy() *BlockStorageMapping {
	if in == nil {
		return nil
	}
	out := new(BlockStorageMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSpec) DeepCopyInto(out *CredentialsSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSpec.
func (in *CredentialsSpec) DeepCopy() *CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCloudServer) DeepCopyInto(out *NCloudServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCloudServer.
func (in *NCloudServer) DeepCopy() *NCloudServer {
	if in == nil {
		return nil
	}
	out := new(NCloudServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NCloudServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCloudServerList) DeepCopyInto(out *NCloudServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NCloudServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCloudServerList.
func (in *NCloudServerList) DeepCopy() *NCloudServerList {
	if in == nil {
		return nil
	}
	out := new(NCloudServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NCloudServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCloudServerSpec) DeepCopyInto(out *NCloudServerSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CredentialsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInterfaceList != nil {
		in, out := &in.NetworkInterfaceList, &out.NetworkInterfaceList
		*out = make([]NetworkInterfaceConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AccessControlGroupNoList != nil {
		in, out := &in.AccessControlGroupNoList, &out.AccessControlGroupNoList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockDevicePartitionList != nil {
		in, out := &in.BlockDevicePartitionList, &out.BlockDevicePartitionList
		*out = make([]BlockDevicePartition, len(*in))
		copy(*out, *in)
	}
	if in.BlockStorageMappingList != nil {
		in, out := &in.BlockStorageMappingList, &out.BlockStorageMappingList
		*out = make([]BlockStorageMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCloudServerSpec.
func (in *NCloudServerSpec) DeepCopy() *NCloudServerSpec {
	if in == nil {
		return nil
	}
	out := new(NCloudServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCloudServerStatus) DeepCopyInto(out *NCloudServerStatus) {
	*out = *in
	out.ServerInstanceStatus = in.ServerInstanceStatus
	out.ServerInstanceOperation = in.ServerInstanceOperation
	out.ServerInstanceType = in.ServerInstanceType
	out.PlatformType = in.PlatformType
	out.HypervisorType = in.HypervisorType
	if in.NetworkInterfaceNoList != nil {
		in, out := &in.NetworkInterfaceNoList, &out.NetworkInterfaceNoList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCloudServerStatus.
func (in *NCloudServerStatus) DeepCopy() *NCloudServerStatus {
	if in == nil {
		return nil
	}
	out := new(NCloudServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceConfiguration) DeepCopyInto(out *NetworkInterfaceConfiguration) {
	*out = *in
	if in.AccessControlGroupNoList != nil {
		in, out := &in.AccessControlGroupNoList, &out.AccessControlGroupNoList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceConfiguration.
func (in *NetworkInterfaceConfiguration) DeepCopy() *NetworkInterfaceConfiguration {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCode) DeepCopyInto(out *StatusCode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCode.
func (in *StatusCode) DeepCopy() *StatusCode {
	if in == nil {
		return nil
	}
	out := new(StatusCode)
	in.DeepCopyInto(out)
	return out
}
