{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ncloud-server-controller.fullname" . }}-manager-rolebinding
  {{- with .Values.rbac.clusterRoleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ncloud-server-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "ncloud-server-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
