{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ncloud-server-controller.fullname" . }}-metrics-service
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "ncloud-server-controller.selectorLabels" . | nindent 4 }}
{{- end }}
